const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
const CHANGE_ACTIVE_CATEGORIES = 'CHANGE_ACTIVE_CATEGORIES';
const SET_POKE_TO_CACHE = 'SET_POKE_TO_CACHE';

export {
  FETCH_CATEGORIES,
  FETCH_CATEGORIES_FAILURE,
  FETCH_CATEGORIES_SUCCESS,
  CHANGE_ACTIVE_CATEGORIES,
  SET_POKE_TO_CACHE,
};
