const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
const CHANGE_ACTIVE_CATEGORIES = 'CHANGE_ACTIVE_CATEGORIES';
const SET_INFO_TO_CACHE = 'SET_INFO_TO_CACHE';
const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';

export {
  FETCH_CATEGORIES_FAILURE,
  FETCH_CATEGORIES_SUCCESS,
  CHANGE_ACTIVE_CATEGORIES,
  SET_INFO_TO_CACHE,
  SET_SEARCH_QUERY,
};
