const FETCH_POKES = 'pokes/FETCH_POKES';
const FETCH_POKES_SUCCESS = 'pokes/FETCH_POKES_SUCCESS';
const FETCH_POKES_FAILURE = 'pokes/FETCH_POKES_FAILURE';

export {
  FETCH_POKES,
  FETCH_POKES_FAILURE,
  FETCH_POKES_SUCCESS,
};
